export const Endpoints = {
  Analitics: "/analytics/",
  Api: "/api",
  BaseURL: process.env.REACT_APP_API,
  Home :'analytics/home',
  Hacienda: "/hacienda/",
  ImportUsers: '/auth/register/import',
  Lectura: "/lecturas/",
  login: "/auth/login/",
  lotes: "/lotes/",
  Permissions: "/auth/permissions",
  perfil: "/auth/porfile/",
  Plantas: "/plantas/",
  Poligonos: "/geolotes/",
  Produccion: "/produccion/",
  Proyecto: "/proyectos/",
  register: "/auth/register/",
  Roles: '/auth/roles',
  Root: '/auth/admin/',
  Test: "/xd/",
  Token: "/auth/refresh/",
  Upload: "upload",
  Users: '/auth/users',
  WeatherData: '/weather/data/',
  WeatherSync: '/weather/sync/',
  WeatherUpload: '/weather/upload/',
};
